version: '3.8'
services:
  comfyui:
    image: zhibeiyou-docker.pkg.coding.net/gaoweiyoutongyiziyuanguanli/gwdocker/comfyui:0.0.5
    container_name: comfyui
   # command: python /opt/ComfyUI/main.py --listen --port 8188
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8188:8188"
    volumes:
      - /home/shanhai/models/moves/comfyui/models:/opt/ComfyUI/models
      - /home/shanhai/models/moves/comfyui/output:/opt/ComfyUI/output
      - /home/shanhai/models/moves/comfyui/custom_nodes:/opt/ComfyUI/custom_nodes
      #- /u01/workspace/ComfyUI/extra_model_paths.yaml:/app/ComfyUI/extra_model_paths.yaml
    networks:
      - comfyui_network
networks:
  comfyui_network:
    driver: bridge

    
